export default [
  {
    "id": "1",
    "name": "Person 1",
    "email": "email1@semailservice.com",
    "city": "City 1",
    "description": "Alright, c'mon, I think we're safe. Holy shit. That Biff, what a character. Always trying to get away with something. Been on top of Biff ever since high school. Although, if it wasn't for him- That's right, he's gonna be mayor. It's already mutated into human form, shoot it.<br>Thanks. Calvin. Yeah, but I never picked a fight in my entire life. Doc, you don't just walk into a store and ask for plutonium. Did you rip this off? Good morning, Mom. Oh, Marty, I almost forgot, Jennifer Parker called.<br>Look me up when you get there, guess I'll be about 47. Alright, McFly, you're asking for it, and now you're gonna get it. Good evening, I'm Doctor Emmet Brown, I'm standing here on the parking lot of- Yeah, you got my homework finished, McFly? What did you sleep in your clothes again last night."
  },
  {
    "id": "2",
    "name": "Person 2",
    "email": "email2@semailservice.com",
    "city": "City 2",
    "description": "I don't wanna see you in here again. Great good, good, Lorraine, I had a feeling about you two. You want it, you know you want it, and you know you want me to give it to you. When could weathermen predict the weather, let alone the future. Oh, thank you, thank you. Okay now, we run some industrial strength electrical cable from the top of the clocktower down to spreading it over the street between two lamp posts. Meanwhile, we out-fitted the vehicle with this big pole and hook which runs directly into the flux-capacitor. At the calculated moment, you start off from down the street driving toward the cable execrating to eighty-eight miles per hour. According to the flyer, at !0:04 pm lightning will strike the clocktower sending one point twenty-one gigawatts into the flux-capacitor, sending you back to 1985. Alright now, watch this. You wind up the car and release it, I'll simulate the lightening. Ready, set, release. Huhh.<br>Okay, okay you guys, oh ha ha ha very funny. Hey you guys are being real mature. Who do you think, the Libyans. What did you sleep in your clothes again last night. Uh, no, no, no, no. What are you looking at, butt-head? Look, there's a rhythmic ceremonial ritual coming up.<br>Whoa, this is heavy. Alright, punk, now- Ah, honey, your first novel. Oh, what I meant to day was- Y'know this time it wasn't my fault. The Doc set all of his clocks twenty-five minutes slow."
  },
  {
    "id": "3",
    "name": "Person 3",
    "email": "email3@semailservice.com",
    "city": "City 3",
    "description": "Wrecked? When did this happen and- C'mon, c'mon let's go. Our first television set, Dad just picked it up today. Do you have a television? Then how am I supposed to ever meet anybody. Uh, no, no, no, no. What are you looking at, butt-head?<br>He's absolutely right, Marty. the last thing you need is headaches. Oh, thank you, thank you. Okay now, we run some industrial strength electrical cable from the top of the clocktower down to spreading it over the street between two lamp posts. Meanwhile, we out-fitted the vehicle with this big pole and hook which runs directly into the flux-capacitor. At the calculated moment, you start off from down the street driving toward the cable execrating to eighty-eight miles per hour. According to the flyer, at !0:04 pm lightning will strike the clocktower sending one point twenty-one gigawatts into the flux-capacitor, sending you back to 1985. Alright now, watch this. You wind up the car and release it, I'll simulate the lightening. Ready, set, release. Huhh. Hey, don't I know you from somewhere? The way I see it, if you're gonna build a time machine into a car why not do it with some style. Besides, the stainless, steel construction made the flux dispersal- look out. Yeah, but you're uh, you're so, you're so thin.<br>Biff. George, there's nothing to be scared of. All it takes is a little self confidence. You know, if you put your mind to it, you could accomplish anything. Thank you, don't forget to take a flyer. Indeed I will, roll em. I, Doctor Emmett Brown, am about to embark on an historic journey. What have I been thinking of, I almost forgot to bring some extra plutonium. How did I ever expect to get back, one pallet one trip I must be out of my mind. What is it Einy? Oh my god, they found me, I don't know how but they found me. Run for it, Marty. Oh, then I wanna give her a call, I don't want her to worry about you."
  }
];